### PR TITLE
drop roboto

### LINKED ISSUE #61: [cls] Remove Roboto(and other not system) font.

### PR DESCRIPTION
**Pull request by AucT**
Closes #61

## Summary by CodeRabbit

- **New Features**
	- Enhanced typography with a broader font stack across multiple components for improved text rendering and compatibility.
	- Improved layout responsiveness through refined media queries and flexbox properties in various sections of the application.

- **Bug Fixes**
	- Adjusted visibility and display properties for elements based on screen size, ensuring a better user experience on mobile devices.

- **Refactor**
	- Streamlined CSS rules and removed redundant styles for improved maintainability and performance.

- **Style**
	- Updated padding, margins, and display properties to enhance visual consistency and aesthetics across the application.

### CODE REVIEW

**Comment by AucT** [comment]
localhost_1313_
localhost_1313_use-cases_

**Comment by AucT** [comment]
Homepage:
localhost_1313_ (1)

**Comment by AucT** [comment]
use cases:
localhost_1313_use-cases_ (2)

**Review by dgorodnichy — APPROVED** [review]
LGTM

**Pull request merged**
