### PR TITLE
Adds jpeg format

### LINKED ISSUE #44: CLS Issue: provide avif and jpeg images for used images
In #43  allowed to use `webp` images. Now left to add: `avif`, `jpg` versions

Parent issue: #32 
Related to #57

### PR DESCRIPTION
**Pull request by AucT**
Use picture instead of img
Add configrutable array of sizes and formats in render-image Refactor code to use configurable array of sizes and formats

Closes #44

## Summary by CodeRabbit

- **New Features**
	- Enhanced image rendering capabilities with support for multiple formats (WebP and JPEG) and sizes (400, 800, 1200, 1600).
	- Implemented a responsive image structure using the `<picture>` element for improved browser compatibility.

- **Improvements**
	- Optimized image handling for better performance and user experience across various devices.

### CODE REVIEW

**Comment by AucT** [comment]
screenshot
S3aPtRWCXE

**Comment by pftg** [comment]
Do not see jpg variants formats also there is no picture tag on screenshot, is it correct?

**Review by pftg — CHANGES_REQUESTED** [review]
Screenshot is not valid

**Comment by AucT** [comment]
screen was from other branch
here screen from this branch

XpMADe8smW

**Pull request merged**
