### PR TITLE
remove not needed blog files

### LINKED ISSUE #96: [REFACT] Remove usage from the old image locations on dev.to
We moved our images to new locations and need to use them for `dev.to`. We need to update `dev.to` posts with new locations. And delete legacy files.

### PR DESCRIPTION
**Pull request by AucT**
Closes #96

### CODE REVIEW

**Comment by dgorodnichy** [comment]
# We should not delete these files unless we are updating articles on dev.to. This action will break our dev.to articles.

**Comment by pftg** [comment]
@AucT we need to remove assets from wp-content and wp-lugin, aka only Wordpress leftovers

**Review by pftg — CHANGES_REQUESTED** [review]
Files from wordpress have not been deleted, and deleted images which are required for dev.to. Please review issue description

**Comment by pftg** [comment]
Closing for now, until we will fix dev.to posts

**Pull request closed without merging**
